#! /bin/bash
#SBATCH --job-name=akita
#SBATCH --output=logFiles/akita.out
#SBATCH --time=04:00:00
#SBATCH --partition=gpu2
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=2000

dirname="/../../../project2/depablo/erschultz/dataset_04_18_21"

# architecture
k=2
n=1024
yPreprocessing='diag'
yNorm='batch'
kernelWList='5-5-5'
hiddenSizesList='32-64-128'
dilationListTrunk='2-4-8-16-32-64-128-256-512'
bottleneck=64
dilationListHead='2-4-8-16-32-64-128-256-512'

# hyperparameters
nEpochs=1
lr=0.1
batchSize=1
numWorkers=4
milestones='25-50'
gamma=0.1

ofile="DeepC_nEpochs${nEpochs}_lr${lr}_milestones${milestones}_yPreprocessing${yPreprocessing}_kernelW${kernelWList}_hiddenSize${hiddenSizesList}_dilationTrunk${dilationListTrunk}_bottleneck${bottleneck}_dilationHead${dilationListHead}"
logfile="logFiles/${ofile}.log"

cd ~/sequences_to_contact_maps
source activate seq2contact_pytorch
python3 Akita.py --data_folder $dirname --k $k --n $n --y_preprocessing ${yPreprocessing} --y_norm $yNorm --kernel_w_list $kernelWList --hidden_sizes_list $hiddenSizesList --dilation_list_trunk $dilationListTrunk --bottleneck $bottleneck --dilation_list_head $dilationListHead --n_epochs $nEpochs --lr $lr --batch_size $batchSize --num_workers $numWorkers --milestones $milestones --gamma $gamma --ofile $ofile

yPreprocessing='prcnt'

ofile="DeepC_nEpochs${nEpochs}_lr${lr}_milestones${milestones}_yPreprocessing${yPreprocessing}_kernelW${kernelWList}_hiddenSize${hiddenSizesList}_dilation${dilationList}_hiddenSize_${hiddenSizeDilation}"
logfile="logFiles/${ofile}.log"

python3 Akita.py --data_folder $dirname --k $k --n $n --y_preprocessing ${yPreprocessing} --y_norm $yNorm --kernel_w_list $kernelWList --hidden_sizes_list $hiddenSizesList --dilation_list_trunk $dilationListTrunk --bottleneck $bottleneck --dilation_list_head $dilationListHead --n_epochs $nEpochs --lr $lr --batch_size $batchSize --num_workers $numWorkers --milestones $milestones --gamma $gamma --ofile $ofile
