#! /bin/bash
#SBATCH --job-name=GNNAutoencoder
#SBATCH --output=logFiles/GNNAutoencoder.out
#SBATCH --time=20:00:00
#SBATCH --partition=depablo-gpu
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=2000

dirname="/../../../project2/depablo/erschultz/dataset_04_18_21"
modelType='GNNAutoencoder'
mode='GNN'

# architecture
k=2
n=1024
yPreprocessing='diag'
yNorm='instance'
hiddenSizesList='16-32'
loss='BCE'
outAct='none'

# hyperparameters
nEpochs=1
batchSize=8
numWorkers=4
milestones=None
gamma=0.1

verbose='true'

cd ~/sequences_to_contact_maps
source activate python3.8_pytorch1.8.1_cuda10.2


for lr in 1e-1
do
python3 core_test_train.py --data_folder $dirname --model_type $modelType --mode $mode --k $k --n $n --y_preprocessing ${yPreprocessing} --y_norm $yNorm --hidden_sizes_list $hiddenSizesList --loss $loss --out_act $outAct --n_epochs $nEpochs --lr $lr --batch_size $batchSize --num_workers $numWorkers --milestones $milestones --gamma $gamma --verbose $verbose
done
