#! /bin/bash
#SBATCH --job-name=plotting
#SBATCH --partition=depablo-gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=2000
#SBATCH --gres=gpu:1
#SBATCH --output=logFiles/plotting.log
#SBATCH --time=03:00:00

dirname="../../../project2/depablo/erschultz/dataset_04_18_21"

# partition
gpus=1

# model
modelType='GNNAutoencoder'
mode='GNN'
pretrained='true'

# other
plotPredictions='true'


cd ~/sequences_to_contact_maps
source activate python3.8_pytorch1.8.1_cuda10.2

for id in 15 16 17
do
  python3 plotting_functions.py  --data_folder $dirname  --gpus $gpus --model_type $modelType --mode $mode --id $id --pretrained $pretrained -plot_predictions $plotPredictions
done
