#! /bin/bash
#SBATCH --job-name=plotting
#SBATCH --partition=depablo-ivyb
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
#SBATCH --mem-per-cpu=2000
#SBATCH --output=logFiles/plotting.log
#SBATCH --time=02:00:00

dirname="../../../project2/depablo/erschultz/dataset_04_18_21"

# partition
gpus=0

# model type
modelType='UNet'

# preprocessing
toxx='true'
xReshape='false'

# architecture
k=2
n=1024
yNorm='instance'
nf=8

# hyperparameters
nEpochs=15
lr=0.1
batchSize=32
numWorkers=20
milestones='5-10'
gamma=0.1


cd ~/sequences_to_contact_maps
source activate seq2contact_pytorch

yPreprocessing='diag'
python3 plotting_script.py  --data_folder $dirname --gpus $gpus --model_type $modelType --toxx $toxx --x_reshape $xReshape --k $k --n $n --y_preprocessing ${yPreprocessing} --y_norm $yNorm --nf $nf --n_epochs $nEpochs --lr $lr --batch_size $batchSize --num_workers $numWorkers --milestones $milestones --gamma $gamma


yPreprocessing='prcnt'
python3 plotting_script.py  --data_folder $dirname  --gpus $gpus --model_type $modelType --toxx $toxx --x_reshape $xReshape --k $k --n $n --y_preprocessing ${yPreprocessing} --y_norm $yNorm --nf $nf --n_epochs $nEpochs --lr $lr --batch_size $batchSize --num_workers $numWorkers --milestones $milestones --gamma $gamma
