#! /bin/bash
#SBATCH --job-name=preprocess
#SBATCH --partition=gpu2
#SBATCH --gres=gpu:1
#SBATCH --mem-per-gpu=1000
#SBATCH --mem-per-cpu=3000
#SBATCH --output=logFiles/preprocess.log
#SBATCH --time=01:00:00

source activate seq2contact_pytorch
python3 preprocess_data.py "../../../project2/depablo/skyhl/dataset_04_07_21"
