#! /bin/bash
#SBATCH --job-name=seq2contact1_4_7_21
#SBATCH --output=seq2contact1_4_7_21
#SBATCH --time=02:00:00
#SBATCH --partition=gpu2
#SBATCH --gres=gpu:1
#SBATCH --mem-per-cpu=2000
#SBATCH --mem-per-gpu=2000

source activate seq2contact_pytorch
python3 seq2contact.py
