#! /bin/bash
#SBATCH --job-name=seq2contact1_4_7_21
#SBATCH --output=seq2contac1_4_7_21
#SBATCH --time=01:00:00
#SBATCH --partition=gpu2
#SBATCH --gres=gpu:1
#SBATCH --mem-per-cpu=5000

source activate seq2contact_pytorch
python3 seq2contact.py
