#! /bin/bash
#SBATCH --job-name=simpleEpiNet
#SBATCH --output=logFiles/simpleEpiNet.out
#SBATCH --time=01:00:00
#SBATCH --partition=gpu2
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=2000
#SBATCH --mem-per-gpu=4000

dirname="/../../../project2/depablo/erschultz/dataset_04_18_21"

# architecture
k=2
n=1024
yNorm='diag'
kernelWList='3-5-5'
hiddenSizesList='10-20-30'

# hyperparameters
nEpochs=2
lr=0.1
batchSize=32
numWorkers=4
milestones='5-10'
gamma=0.1

ofile="simpleEpiNet_nEpochs${nEpochs}_kernelW${kernelWList}_hiddenSize${hiddenSizesList}_latent${latent}_lr${lr}_milestones${milestones}"
logfile="logFiles/${ofile}.log"

cd ~/sequences_to_contact_maps
source activate seq2contact_pytorch
python3 SimpleEpiNet.py --data_folder $dirname --n_epochs $nEpochs --height $h --hidden $hidden --latent $latent --batch_size $batchSize --num_workers $numWorkers --milestones $milestones --gamma $gamma --k $k --ofile $ofile --crop $crop --n $n >> $logfile
