#! /bin/bash
#SBATCH --job-name=simpleEpiNet
#SBATCH --output=logFiles/simpleEpiNet.out
#SBATCH --time=02:00:00
#SBATCH --partition=gpu2
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --mem-per-cpu=4000
#SBATCH --mem-per-gpu=8000

dirname="/../../../project2/depablo/skyhl/dataset_04_07_21"
nEpochs=15
h=1
hidden=10
latent=5
lr=0.1
batchSize=16
numWorkers=2
milestones='5-10'
gamma=0.1
k=2
crop='128-1024'
n=896

ofile="simpleEpiNet_nEpochs${nEpochs}_h${h}_hidden${hidden}_latent${latent}_lr${lr}_milestones${milestones}_crop${crop}"
logfile="sequences_to_contact_maps/logFiles/${ofile}.log"

cd ~
source activate seq2contact_pytorch
python3 ~/sequences_to_contact_maps/SimpleEpiNet.py --data_folder $dirname --n_epochs $nEpochs --height $h --hidden $hidden --latent $latent --batch_size $batchSize --num_workers $numWorkers --milestones $milestones --gamma $gamma --k $k --ofile $ofile --crop $crop --n $n >> $logfile
