#! /bin/bash
#SBATCH --job-name=test
#SBATCH --output=logFiles/test.out
#SBATCH --time=01:00:00
#SBATCH --partition=gpu2
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=2000

cd ~/sequences_to_contact_maps
source activate seq2contact_pytorch


dirname="/../../../project2/depablo/erschultz/dataset_04_18_21"




cd ~/sequences_to_contact_maps
source activate seq2contact_pytorch

lr=1e-1
python3 neural_net_utils/utils.py --data_folder $dirname
