#! /bin/bash
#SBATCH --job-name=UNet
#SBATCH --output=logFiles/UNet.out
#SBATCH --time=04:00:00
#SBATCH --partition=depablo-gpu
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=2000

dirname="/../../../project2/depablo/erschultz/dataset_04_18_21"

# preprocessing
toxx='true'
xReshape='false'

# architecture
k=2
n=1024
yPreprocessing='diag'
yNorm='instance'
nf=8
loss='mse'

# hyperparameters
nEpochs=15
lr=0.1
batchSize=32
numWorkers=4
milestones='5-10'
gamma=0.1

ofile="UNet_nEpochs${nEpochs}_nf${nf}_lr${lr}_milestones${milestones}_yPreprocessing${yPreprocessing}_yNorm${yNorm}"
logfile="logFiles/${ofile}.log"

cd ~/sequences_to_contact_maps
source activate seq2contact_pytorch
python3 UNet.py --data_folder $dirname --toxx $toxx --x_reshape $xReshape --k $k --n $n --y_preprocessing ${yPreprocessing} --y_norm $yNorm --nf $nf --loss $loss --n_epochs $nEpochs --lr $lr --batch_size $batchSize --num_workers $numWorkers --milestones $milestones --gamma $gamma --ofile $ofile >> $logfile


yPreprocessing='prcnt'
yNorm=None
loss='cross_entropy'

ofile="UNet_nEpochs${nEpochs}_nf${nf}_lr${lr}_milestones${milestones}_yPreprocessing${yPreprocessing}_yNorm${yNorm}"
logfile="logFiles/${ofile}.log"

python3 UNet.py --data_folder $dirname --toxx $toxx --x_reshape $xReshape --k $k --n $n --y_preprocessing ${yPreprocessing} --y_norm $yNorm --nf $nf --loss $loss --n_epochs $nEpochs --lr $lr --batch_size $batchSize --num_workers $numWorkers --milestones $milestones --gamma $gamma --ofile $ofile >> $logfile
