#! /bin/bash
#SBATCH --job-name=seqVAE1_4_6_21
#SBATCH --output=seqVAE1_4_6_21
#SBATCH --time=00:01:00
#SBATCH --partition=gpu2
#SBATCH --gres=gpu:1

conda init bash
conda activate seq2contact_pytorch
python3 seqVAE.py
