#! /bin/bash
#SBATCH --job-name=seqVAE1_4_7_21
#SBATCH --output=seqVAE1_4_7_21
#SBATCH --time=01:00:00
#SBATCH --partition=gpu2
#SBATCH --gres=gpu:1

source activate seq2contact_pytorch
python3 seqVAE.py
